name: CI para Backend

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t geminis-backend:latest -f RoadRunner.Dockerfile .

      - name: Create Docker network
        run: docker network create github_network

      - name: Start MySQL container
        run: docker run -d --name mysql --network github_network -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=geminis -e MYSQL_USER=userGeminis -e MYSQL_PASSWORD=secret mysql:8

      - name: Wait for MySQL to be ready
        run: |
          until docker run --rm --network github_network mysql:8 mysqladmin ping -h mysql --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Start backend container
        run: docker run -d --name geminis-backend --network github_network geminis-backend:latest

      - name: Configure environment and run tests
        run: |
          docker cp backend/.env.example geminis-backend:/var/www/.env
          docker exec geminis-backend sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' /var/www/.env
          docker exec geminis-backend php artisan key:generate
          docker exec geminis-backend php artisan migrate --force
          docker exec geminis-backend vendor/bin/phpunit --log-junit /var/www/test-results-unit.xml
          docker exec geminis-backend php vendor/bin/phpunit --testsuite integration --log-junit /var/www/test-results-integration.xml

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          tools: composer

      - name: Install PHP_CodeSniffer and PHPCBF
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Run PHPCBF to fix coding standard issues
        run: phpcbf --standard=PSR12 backend/

      - name: Run PHP_CodeSniffer
        id: phpcs
        run: phpcs --standard=PSR12 backend/ || true

      - name: Check PHPCS Output
        if: steps.phpcs.outcome == 'failure'
        run: echo "PHP_CodeSniffer found issues."

      - name: Send alert to Teams if PHP_CodeSniffer fails
        if: steps.phpcs.outcome == 'failure'
        run: |
          curl -H 'Content-Type: application/json' \
            -d '{"text": "PHP_CodeSniffer analysis failed for commit '${{ github.sha }}'. Please check the details in the pipeline logs."}' \
            ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./*.xml

      - name: Post test results to PR or Commit
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const unitTestResults = fs.readFileSync('test-results-unit.xml', 'utf8');
            const integrationTestResults = fs.readFileSync('test-results-integration.xml', 'utf8');
            const body = `
            ## Unit Test Results:
            ${unitTestResults}

            ## Integration Test Results:
            ${integrationTestResults}
            `;

            if (context.eventName === 'pull_request') {
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: body
              });
            } else if (context.eventName === 'push') {
              const commitSha = context.sha;
              github.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commitSha,
                body: body
              });

      - name: Clean up Docker containers and network
        if: always()
        run: |
          docker rm -f geminis-backend || true
          docker rm -f mysql || true
          docker network rm github_network || true
