name: "Backend Continuous Integration"

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, zip, exif, pcntl, opcache

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --working-dir=./backend

      - name: Copy environment file
        run: cp ./backend/.env.example ./backend/.env

      - name: Generate application key
        run: php ./backend/artisan key:generate

      - name: Run unit tests
        run: ./backend/vendor/bin/phpunit --coverage-text --coverage-clover=./backend/coverage.xml

      - name: Copy Dockerfile and deployment files to backend
        run: |
          cp ./RoadRunner.Dockerfile ./backend/RoadRunner.Dockerfile
          mkdir -p ./backend/deployment
          cp -r ./deployment/* ./backend/deployment/

      - name: Build Docker image
        run: docker build -t geminis-backend -f ./backend/RoadRunner.Dockerfile ./backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./backend/coverage.xml

      - name: Create a comment with the test results
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('./backend/coverage.xml', 'utf8');
            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `### Test Coverage Report\n\`\`\`\n${report}\n\`\`\``
            });
