name: CI para Backend

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build-and-test:
    name: Construir y Probar
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: geminis
          MYSQL_USER: userGeminis
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Extraer código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verificar que Dockerfile exista
        run: ls -l RoadRunner.Dockerfile

      - name: Construir imagen Docker
        run: docker build -t geminis-backend:latest -f RoadRunner.Dockerfile .

      - name: Esperar a que MySQL esté listo
        run: |
          until docker run --rm --network ${{ job.services.mysql.networks.default }} mysql:8 mysqladmin ping -h mysql --silent; do
            echo "Esperando a que MySQL esté listo..."
            sleep 5
          done
          echo "¡MySQL está listo!"

      - name: Iniciar contenedor backend
        run: docker run -d --name geminis-backend --network ${{ job.services.mysql.networks.default }} --env-file .env geminis-backend:latest

      - name: Copiar .env.example y renombrarlo a .env
        run: docker cp backend/.env.example geminis-backend:/var/www/.env

      - name: Actualizar .env para MySQL
        run: docker exec geminis-backend sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' /var/www/.env

      - name: Ejecutar migraciones
        run: docker exec geminis-backend php artisan migrate --force

      - name: Ejecutar pruebas unitarias
        run: docker exec geminis-backend vendor/bin/phpunit
