name: "Backend Continuous Integration"

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, zip, exif, pcntl, opcache

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: ./backend

      - name: Copy environment file
        run: cp ${GITHUB_WORKSPACE}/backend/.env.example ${GITHUB_WORKSPACE}/backend/.env

      - name: Generate application key
        run: php artisan key:generate
        working-directory: ${GITHUB_WORKSPACE}/backend

      - name: Run unit tests
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
        working-directory: ${GITHUB_WORKSPACE}/backend

      - name: Copy Dockerfile and deployment files to backend
        run: |
          cp ${GITHUB_WORKSPACE}/RoadRunner.Dockerfile ${GITHUB_WORKSPACE}/backend/RoadRunner.Dockerfile
          cp -r ${GITHUB_WORKSPACE}/deployment ${GITHUB_WORKSPACE}/backend/deployment

      - name: Build Docker image
        run: docker build -t geminis-backend -f ${GITHUB_WORKSPACE}/backend/RoadRunner.Dockerfile ${GITHUB_WORKSPACE}/backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${GITHUB_WORKSPACE}/backend/coverage.xml

      - name: Create a comment with the test results
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('${GITHUB_WORKSPACE}/backend/coverage.xml', 'utf8');
            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `### Test Coverage Report\n\`\`\`\n${report}\n\`\`\``
            });
