name: CI for Backend

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create ci-network

      - name: Copy .env file
        run: cp backend/.env.example backend/.env

      - name: Build Docker image
        run: docker build -t geminis-backend:latest -f backend/RoadRunner.Dockerfile .

 
