name: "Backend Continuous Integration"

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, zip, exif, pcntl, opcache

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --working-dir=backend

      - name: Copy environment file
        run: cp $GITHUB_WORKSPACE/backend/.env.example $GITHUB_WORKSPACE/backend/.env

      - name: Generate application key
        run: php $GITHUB_WORKSPACE/backend/artisan key:generate

      - name: Run unit tests
        run: php $GITHUB_WORKSPACE/backend/vendor/bin/phpunit --configuration $GITHUB_WORKSPACE/backend/phpunit.xml --coverage-text --coverage-clover=$GITHUB_WORKSPACE/backend/coverage.xml

      - name: Copy Dockerfile and deployment files to backend
        run: |
          cp $GITHUB_WORKSPACE/RoadRunner.Dockerfile $GITHUB_WORKSPACE/backend/RoadRunner.Dockerfile
          mkdir -p $GITHUB_WORKSPACE/backend/deployment
          cp -r $GITHUB_WORKSPACE/deployment/* $GITHUB_WORKSPACE/backend/deployment/

      - name: Build Docker image
        run: docker build -t geminis-backend -f $GITHUB_WORKSPACE/backend/RoadRunner.Dockerfile $GITHUB_WORKSPACE/backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: $GITHUB_WORKSPACE/backend/coverage.xml

      - name: Create a comment with the test results
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync(process.env.GITHUB_WORKSPACE + '/backend/coverage.xml', 'utf8');
            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `### Test Coverage Report\n\`\`\`\n${report}\n\`\`\``
            });
