name: Continuous Integration

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

env:
  BACKEND_DIR: backend

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Copy .env file
        run: cp .env.example .env
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Generate APP_KEY
        run: php artisan key:generate
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Run tests
        run: vendor/bin/phpunit --coverage-text
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Backend
        run: docker build -f ${{ env.BACKEND_DIR }}/Dockerfile -t backend .

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Copy .env file
        run: cp .env.example .env
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Generate APP_KEY
        run: php artisan key:generate
        working-directory: ${{ env.BACKEND_DIR }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.3
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
